[package]
name = 'dotshellextract'
slug = 'dotshellextract'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Extract your dotfiles for reusability'

[run]
dependencies = ['https://github.com/hyperupcall/bash-args@v0.9.2']
sourceDirs = []
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
